version: '3.8'

services:
  # Сервис эмбеддингов
  embedding-service:
    build: .
    container_name: embedding-service
    ports:
      - "5000:5000"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./models:/root/.cache/huggingface/hub
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://embedding-service:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s # Longer start period for model loading
    restart: unless-stopped
    networks:
      - mcp-network
      
# embedding-service:
#   build: .
#   container_name: embedding-service
#   ports:
#     - "5000:5000"
#   environment:
#     - PYTHONPATH=/app
#     - PYTHONUNBUFFERED=1
#   volumes:
#     # Mount config for easy updates without rebuild
#     - ./config.json:/app/config.json:ro
#   restart: unless-stopped
#   healthcheck:
#     test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
#     interval: 30s
#     timeout: 10s
#     retries: 5
#     start_period: 60s # Longer start period for model loading
#   deploy:
#     resources:
#       limits:
#         memory: 2G
#       reservations:
#         memory: 1G

networks:
  mcp-network:
    driver: bridge